### ISSUE TITLE
Adding "What are you here for feature"

### ISSUE THREAD

**Issue by tea-jazz** [clemsonMakerspace/unified-makerspace#101]
A lot of people sign-in to visit the Makerspace. Though we can determine the number of people who sign into the space a certain times we do not know what exactly they there to do. They could be there to pick up parts or they could actually be using machinery. Ideally it would be great to have another question that asks "What are you here to do today" after they enter their username. This information would be useful in determining what times each equipment is busy so we can plan staffing schedules as well as any investor visits during our busy times. 

It would also be great if the question is location dependent so if someone signs in at Cook the option will show "Waterjet" since that is the only machinery there but if they sign-in at Watt they will see all of the machinery available at Watt. I will provide the list of machines in each space after clarifying with the staff.

**Comment by Mjtlittle** [comment]
All of the functionality for this is pretty much done (#97). The only things left to do are planning when we are going to merge it with our existing planned PRs and changes, and which tools are at each location.

*this is how we are storing the location information if you are curious. Omitting a tool list from a location will skip the survey question.
```ts
export const locations: MakerspaceLocation[] = [
  {
    slug: "watt_center",
    name: "Watt Family Innovation Center",
    tools: ["3D Printer", "Lazer Cutter", "Other"],
  },
  {
    slug: "cooper_library",
    name: "Cooper Library",
    tools: ["3D Printer"],
  },
  {
    slug: "cook_lab",
    name: "Cook Laboratory",
    tools: [],
  },
];
```
