### ISSUE TITLE
Graduation date

### ISSUE THREAD

**Issue by tea-jazz** [clemsonMakerspace/unified-makerspace#56]
When users are registering, it asks for expected graduation in specific date form such as (5/2/2022). It would be preferable to have it ask the semester and year such as (Spring-2022). This would make analyzing data easier since many people don't know the exact date of graduation.

**Comment by KellenJames** [comment]
#64 
I went ahead and swapped the expected graduation date with expected graduation year and semester dropdowns.
I'm pretty new to working with web dev content, so for simplicity reasons I just added the years 2022-2030 into the dropdown list, but it would probably be better to have it dynamically update every year, which I can go back and try to change at a later time.
