### ISSUE TITLE
Build React Site in CodePipeline

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/unified-makerspace#62]
Currently the https://visit.cuMaker.space/ react site build is triggered manually & the build artifacts are version controlled at [cdk/visit/console/](https://github.com/clemsonMakerspace/unified-makerspace/tree/mainline/cdk/visit/console/). This makes our git diffs obnoxiously large, raises the barrier to entry for new devs, and is likely to be very error-prone.

Ideally our React app would be built by [the CodePipeline](https://github.com/clemsonMakerspace/unified-makerspace/blob/mainline/cdk/Pipeline.py#L38-L42) and the beta and prod stages would be set via env var at build-time as specified in #61.

Our dev stacks aren't build by CodePipelines - how can we simplify build & deployment of the dev stacks?

**Comment by Mjtlittle** [comment]
I added this when I was in capstone :) 
Minus the dev stack automation, maybe better docs or dx for setting the dev stack, currently you have to edit an accounts file which im not a fan of also
